a little more user-insulation

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -30,7 +30,10 @@ parse_args() {
 
 detail_log() {
     logfile=/tmp/bootstrap$$.log 
-    exec 3>&1 > $logfile 2>&1
+    # use fd 3 for messages to user, send stdout and stderr to log
+    # redirect stdin from /dev/null, so anything that tries to prompt
+    # for input will fail and not hang because no message gets to the user
+    exec 3>&1 > $logfile 2>&1 < /dev/null
     echo "Putting detail log in /tmp/bootstrap$$.log" >&3 
 }
 
@@ -65,6 +68,17 @@ message() {
     echo $* >&3
     start_monitor $logfile 458
 }
+
+check_bootstrap() {
+    if [ `spack find | egrep 'patchelf|spack-infrastructure' | wc -l` = 2 ]
+    then
+        :
+    else
+        message "Bootstrap did NOT complete properly, please attach logfile to a Servicedesk ticket"
+        exit 1
+    fi
+}
+
 main() {
     parse_args "$@"
 
@@ -88,6 +102,8 @@ main() {
     cd $dest/spack-infrastructure/$ver/NULL && bin/declare_simple spack-infrastructure $ver
 
     stop_monitor
+   
+    check_bootstrap
 }
 
 main "$@"
